I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter1.rpy", line 212, in script
    OpiekunRoku "Ludzie kochani. Ilu Was się jeszcze spóźni? Coś kiepsko wróżę Waszą punktualność
Exception: Sayer 'OpiekunRoku' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter1.rpy", line 212, in script
    OpiekunRoku "Ludzie kochani. Ilu Was się jeszcze spóźni? Coś kiepsko wróżę Waszą punktualność
  File "D:\Programy\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Programy\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'OpiekunRoku' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Wonderful Time 1.0
